# $FreeBSD$

PORTNAME=	cmmapi
PORTVERSION=	0.1
CATEGORIES=	net
MASTER_SITES=	http://www.szerafingomba.hu/softwares/cmmapi/

MAINTAINER=	pozsar.zsolt@szerafingomba.hu
COMMENT=	Command line utility for MMAPI library

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
