#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/cmmapi -a -d /usr/share/doc/cmmapi ]; then
    ln -sf /usr/share/doc/cmmapi /usr/doc/cmmapi
  fi
fi
# End automatically added section
